# Generated by Django 4.1.7 on 2023-03-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
