# Generated by Django 4.1.7 on 2023-03-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_manga_total_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
