# Generated by Django 4.1.7 on 2023-03-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('manga', '0007_delete_user_manga_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
