# Generated by Django 4.1.7 on 2023-03-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_manga_current_chapter_alter_manga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='total_chapters',
            field=models.IntegerField(default=0),
        ),
    ]
